package com.szfp.asoriba.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.szfp.asoriba.bean.FingerprintBean;
import com.szfp.asoriba.bean.MemberBean;

import com.szfp.asoriba.greendao.FingerprintBeanDao;
import com.szfp.asoriba.greendao.MemberBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fingerprintBeanDaoConfig;
    private final DaoConfig memberBeanDaoConfig;

    private final FingerprintBeanDao fingerprintBeanDao;
    private final MemberBeanDao memberBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fingerprintBeanDaoConfig = daoConfigMap.get(FingerprintBeanDao.class).clone();
        fingerprintBeanDaoConfig.initIdentityScope(type);

        memberBeanDaoConfig = daoConfigMap.get(MemberBeanDao.class).clone();
        memberBeanDaoConfig.initIdentityScope(type);

        fingerprintBeanDao = new FingerprintBeanDao(fingerprintBeanDaoConfig, this);
        memberBeanDao = new MemberBeanDao(memberBeanDaoConfig, this);

        registerDao(FingerprintBean.class, fingerprintBeanDao);
        registerDao(MemberBean.class, memberBeanDao);
    }
    
    public void clear() {
        fingerprintBeanDaoConfig.clearIdentityScope();
        memberBeanDaoConfig.clearIdentityScope();
    }

    public FingerprintBeanDao getFingerprintBeanDao() {
        return fingerprintBeanDao;
    }

    public MemberBeanDao getMemberBeanDao() {
        return memberBeanDao;
    }

}
