package com.szfp.asoriba.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.szfp.asoriba.bean.FingerprintBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FINGERPRINT_BEAN".
*/
public class FingerprintBeanDao extends AbstractDao<FingerprintBean, Long> {

    public static final String TABLENAME = "FINGERPRINT_BEAN";

    /**
     * Properties of entity FingerprintBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UUID = new Property(1, String.class, "UUID", false, "UUID");
        public final static Property Model = new Property(2, byte[].class, "model", false, "MODEL");
    }


    public FingerprintBeanDao(DaoConfig config) {
        super(config);
    }
    
    public FingerprintBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FINGERPRINT_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"UUID\" TEXT," + // 1: UUID
                "\"MODEL\" BLOB);"); // 2: model
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FINGERPRINT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FingerprintBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String UUID = entity.getUUID();
        if (UUID != null) {
            stmt.bindString(2, UUID);
        }
 
        byte[] model = entity.getModel();
        if (model != null) {
            stmt.bindBlob(3, model);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FingerprintBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String UUID = entity.getUUID();
        if (UUID != null) {
            stmt.bindString(2, UUID);
        }
 
        byte[] model = entity.getModel();
        if (model != null) {
            stmt.bindBlob(3, model);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FingerprintBean readEntity(Cursor cursor, int offset) {
        FingerprintBean entity = new FingerprintBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // UUID
            cursor.isNull(offset + 2) ? null : cursor.getBlob(offset + 2) // model
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FingerprintBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUUID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setModel(cursor.isNull(offset + 2) ? null : cursor.getBlob(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FingerprintBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FingerprintBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FingerprintBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
